# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 679d29b0f06371cc93579fcd38a63ec32dae6798ff61aa813d32e4dbfd993571fe005e96e57d5d63fde41880529a7de82798fe677ea582a68f386e3521c383d0

test:
  secret_key_base: 5a123b7422ec69ef43a9fa94d65e1cf97ddcd74500bda54d0762a2e178c2ad8fabee6b2993937caf028f0673d1012108724013bdcd99c3a0991a9d762259618d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
